[workspace]
members = [
    "lib",
    "cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Gabe Fierro <gtfierro@mines.edu>"]
license = "BSD-3-Clause"
edition = "2021"

[workspace.dependencies]
oxigraph = "0.4.11"
shacl = { version = "0.1.0", path = "lib" }
clap = { version = "4.5.39", features = ["derive"] }
graphviz-rust = "0.9.5"
regex = "1"

[profile.release]
debug = true
