[workspace]
members = [
    "lib",
    "cli",
    "python",
    "shacl-ir"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Gabe Fierro <gtfierro@mines.edu>"]
license = "BSD-3-Clause"
edition = "2021"
description = "A Shapes Constraint Language (SHACL) validator written in Rust"
readme = "README.md"
repository = "https://github.com/gtfierro/shacl-rs"
homepage = "https://github.com/gtfierro/shacl-rs"
documentation = "https://github.com/gtfierro/shacl-rs#readme"

[workspace.dependencies]
oxigraph = "0.5.0"
petgraph = "0.6.5"
shacl = { version = "0.1.0", path = "lib" }
clap = { version = "4.5.39", features = ["derive"] }
graphviz-rust = "0.9.5"
regex = "1"
log = "0.4"
env_logger = "0.11"
url = "2"
sha2 = "0.10.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"

[profile.release]
debug = true
