[package]
name = "cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "shacl"
path = "src/main.rs"
doc = false

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
graphviz-rust = "0.9.5"
shacl.workspace = true
