[package]
name = "cli"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[[bin]]
name = "shacl"
path = "src/main.rs"
doc = false

[dependencies]
clap.workspace = true
graphviz-rust.workspace = true
shacl.workspace = true
