[package]
name = "python"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"

[lib]
name = "shifty"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py311"] }
shifty = { path = "../lib", package = "shifty-shacl" }
oxigraph.workspace = true
ontoenv = "0.5.0-a8"
tempfile = "3"
serde_json.workspace = true
env_logger.workspace = true
